//! Default Typst report template (TRD Section 3.9, 12.1).
//!
//! Built-in Typst report markup with `{{PLACEHOLDER}}` substitution.
//! The template is a valid `.typ` file once all placeholders are resolved
//! by the orchestration layer in `mod.rs`.

/// Returns the built-in Typst template string with `{{PLACEHOLDER}}` markers.
///
/// Placeholders resolved by `mod.rs`:
/// - `{{STRATEGY_SUMMARY}}` — strategy parameter table
/// - `{{METRICS_TABLE}}` — aggregate performance metrics table
/// - `{{EQUITY_CURVE_SVG}}` — inline SVG equity chart
/// - `{{DRAWDOWN_CHART_SVG}}` — inline SVG drawdown chart
/// - `{{UNIVERSE_SUMMARY}}` — per-code summary table (multi-code only)
/// - `{{PER_CODE_SECTIONS}}` — per-code detail sections (multi-code only)
/// - `{{TRADE_LOG}}` — full trade log table
/// - `{{MONTHLY_RETURNS}}` — monthly returns heatmap grid
pub fn template() -> &'static str {
    r##"// SamTrader Backtest Report — generated by samtrader
// This file is valid Typst markup.

#set page(paper: "a4", margin: (x: 1.5cm, y: 2cm))
#set text(font: "Linux Libertine", size: 10pt)
#set heading(numbering: "1.")

= Backtest Report

== Strategy Summary

{{STRATEGY_SUMMARY}}

== Performance Metrics

{{METRICS_TABLE}}

== Equity Curve

#align(center)[
  {{EQUITY_CURVE_SVG}}
]

== Drawdown

#align(center)[
  {{DRAWDOWN_CHART_SVG}}
]

{{UNIVERSE_SUMMARY}}

{{PER_CODE_SECTIONS}}

== Trade Log

{{TRADE_LOG}}

== Monthly Returns

{{MONTHLY_RETURNS}}
"##
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn template_contains_all_placeholders() {
        let t = template();
        assert!(t.contains("{{STRATEGY_SUMMARY}}"));
        assert!(t.contains("{{METRICS_TABLE}}"));
        assert!(t.contains("{{EQUITY_CURVE_SVG}}"));
        assert!(t.contains("{{DRAWDOWN_CHART_SVG}}"));
        assert!(t.contains("{{UNIVERSE_SUMMARY}}"));
        assert!(t.contains("{{PER_CODE_SECTIONS}}"));
        assert!(t.contains("{{TRADE_LOG}}"));
        assert!(t.contains("{{MONTHLY_RETURNS}}"));
    }

    #[test]
    fn template_is_valid_typst_preamble() {
        let t = template();
        assert!(t.contains("#set page("));
        assert!(t.contains("#set text("));
        assert!(t.contains("= Backtest Report"));
    }
}
